# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require "pathname"

path = Pathname(__dir__) / "lib" / "tasks" / "**" / "*.rake"

Pathname.glob(path).each do |file|
  load file
end
