#!/usr/bin/env ruby

require_relative "../lib/suspenders"

if ARGV.length > 2 || ARGV.length == 0
  puts "Error: Invalid command"
  puts "Available commands are"
  puts "suspenders new APP_NAME"
  puts "suspenders -v"
  exit 1
end

command = ARGV[0]
app_name = ARGV[1]

if ["-v", "--version"].include?(command)
  puts Suspenders::VERSION
  exit 0
elsif ["new"].include?(command)
  if app_name.nil? || app_name.empty?
    puts "Error: Application name required"
    puts "Usage: suspenders new APP_NAME"
    exit 1
  end
end

begin
  Suspenders::CLI.run(app_name)
  exit 0
rescue Suspenders::Error => e
  abort "Error: #{e.message}"
end
