#!/usr/bin/env sh

# Set up Rails app. Run this script immediately after cloning the codebase.
# https://github.com/thoughtbot/guides/tree/master/protocol

bundle install --binstubs=bin/stubs
rake db:setup
cp sample.env .env
